### ISSUE TITLE
Pause button issue

### ISSUE THREAD

**Issue by mytja** [alexmercerind/harmonoid#14]
Hello!
I found a bug.
When my music from album is playing, and if I downloaded only one song from it, when I go to Now Playing tab and pause it, then click next, button for Pause is still same, but music is playing, this is very annoying, since I have to click 2 times, when, I want to pause.
Can you fix this?

**Comment by alexmercerind** [comment]
Hi @mytja !
Thanks for your report. I can also reproduce the issue. And it is indeed annoying.
I will try to fix this bug in the next release definitely. 
Next release will have many new features & enhancements along with bug fixes. 
Thankyou! 😃

**Comment by mytja** [comment]
Hi, @alexmercerind 
Awesome! Hope you did well!

**Comment by alexmercerind** [comment]
:tada: alexmercerind@cbcc8f4792e9b37343f1db66eec69ab1485a5794 !

This commit should fix all the issues to playback button on 'Now Playing' screen.
Re-open issue in case you experience this again in the next release.

Thankyou!
