### ISSUE TITLE
Localization bug (cropped label) 

### ISSUE THREAD

**Issue by raitonoberu** [alexmercerind/harmonoid#19]
Hi, @alexmercerind!
I found a little bug. The label above the accent choosing is cropped.
![IMG_20200908_102539.jpg](https://user-images.githubusercontent.com/64320078/92430239-65aae400-f1be-11ea-9832-0dbefd438e3f.jpg)

So, the label translates to "You must restart the app to". It seems that the Slovenian lang is bugged too.

Thanks!

**Comment by mytja** [comment]
Yes, slovenian label is also bugged

**Comment by alexmercerind** [comment]
Hi everybody!
It's just a one line fix.
This release has some other bugs too. I think I have to release a v0.0.2+2.

Sorry guys for the inconvenience you experienced.

**Comment by alexmercerind** [comment]
@raitonoberu @mytja 

alexmercerind@59d63f804d8d88ce00592b096175a1f9d773452c

![Screenshot_20200908-105530](https://user-images.githubusercontent.com/28951144/92436481-6ba2c400-f1c2-11ea-961a-d1a03b653b32.jpg)
