### ISSUE TITLE
Album deleting button is invisible if album art is white colored

### ISSUE THREAD

**Issue by mytja** [alexmercerind/harmonoid#22]
When I want to delete a song, that has a white background, I don't see trash can, even though it's there. Example:![Screenshot_20200908-101945.jpg](https://user-images.githubusercontent.com/52399966/92451475-0a2c2680-f1bd-11ea-8a48-b0ed44665201.jpg)

**Comment by alexmercerind** [comment]
I think I should set the color of trash icon, as the opposite of "album art's dominant color". 

Should be an easy improvement, can be easily set during ```initState()``` of the widget.
I'll again use [pallete_generator](https://pub.dev/packages/palette_generator) for getting dominant color of an image.

Thankyou.

**Comment by mytja** [comment]
@alexmercerind At dependencies, in readme, you linked Just Audio to Audio Service

**Comment by alexmercerind** [comment]
@mytja,
I tried to make simple function to check if an image is "dark" or "light" & change the color of icons accordingly but it seems that it isn't working out, as it is not stable. It is not 100% in telling which image is "light" or "dark". (It was in-fact telling that luminance of the album art that you gave above is <0.5 i.e. dark, but we can clearly see that it is more like light)

A guy has discussed same problem [here](https://stackoverflow.com/questions/54438359/how-to-change-text-color-based-on-background-image-flutter).

This is not a high priority issue right now & there is nothing I can do.

**Comment by mytja** [comment]
Okay
