### ISSUE TITLE
Change "Deutsche" to "Deutsch"

### ISSUE THREAD

**Issue by MickLesk** [alexmercerind/harmonoid#24]
https://github.com/alexmercerind/harmonoid/blob/50d90d220b291e2429c88ce084a7b65a49d7ae85/lib/setting.dart#L750
https://github.com/alexmercerind/harmonoid/blob/50d90d220b291e2429c88ce084a7b65a49d7ae85/lib/about.dart#L845

Hi @alexmercerind , can you change "Deutsche" to "Deutsch"?

**Comment by alexmercerind** [comment]
Okay dude! 👌

**Comment by mytja** [comment]
And also Slovenščina is in slovenian written with lower case letters: "slovenščina"

**Comment by alexmercerind** [comment]
@mytja,
It's all because of Google's translator.

**Comment by mytja** [comment]
![Screenshot_20200908-162041.jpg](https://user-images.githubusercontent.com/52399966/92488771-437d8a00-f1ef-11ea-8a3e-a3d956aecd25.jpg)

**Comment by alexmercerind** [comment]
@mytja,
Isn't that correct?
What do you want me to do?
Change to what from what.

**Comment by mytja** [comment]
Slovenščina must be written with lower case letters

**Comment by alexmercerind** [comment]
@mytja! Okay, I'm sorry for the inconvenience. 😅

**Comment by alexmercerind** [comment]
@mytja alexmercerind@c355787754ee0dd4ad43b899dc261550dcc0b27b ✔

**Comment by MickLesk** [comment]
Deutsch must be lower case too :-)

**Comment by alexmercerind** [comment]
@MickLesk, okay.

Apart from that, are you guys sure about it? Because as far as I know, first letter capitalization is counted as a remark of respect in English & I wanna respect everyone.

**Comment by MickLesk** [comment]
The language is Lower case, the Country is higher case

**Comment by alexmercerind** [comment]
@MickLesk,
😃 Okay!
