### ISSUE TITLE
Feature-Request: After Change App-Mode or Acent-Color -> Restart Button

### ISSUE THREAD

**Issue by MickLesk** [alexmercerind/harmonoid#25]
Hey @alexmercerind ,

when I was building the app earlier (German translation) I noticed that you introduced accent colors.
Now you have to exit the app by yourself. Here a dialog would be nice.
"Would you like to restart the app now? - "Yes" - "No".

**Comment by alexmercerind** [comment]
Okay, I'll see. I've marked this as an "improvement".

Along with accent colors, there is now a gorgeous dark theme. .👌

**Comment by MickLesk** [comment]
Yes, it look great, but i have another idea, the Splashscreen should be in dark-mode too. 
When it is evening and I have the app in dark mode and a bright splash screen opens, my eyes hurt :-D

**Comment by alexmercerind** [comment]
@MickLesk,
Yeah! That thing came in my mind aswell. But, since this project is in Flutter, it is hard for me to deal with native Android things like dynamic splash screen, I'll see how to add that up.

**Comment by MickLesk** [comment]
@alexmercerind  Checkout my changes... (only android)
https://github.com/MickLesk/harmonoid/commit/507bbf41a489fdb2c47d0804e5fcb4a069ed3637

**Comment by alexmercerind** [comment]
@MickLesk,
Yeah yeah! But the challenge is to change it dynamically on startup not set it just at the time of compiling.

**Comment by MickLesk** [comment]
> @MickLesk,
> Yeah yeah! But the challenge is to change it dynamically on startup not to set it just at the time of compiling.

I take a look at the next days, i read your Code asap..

**Comment by alexmercerind** [comment]
@MickLesk,
I've started to work on this one.

**Comment by MickLesk** [comment]
@alexmercerind  you've deleted the last issue. Where can i reach you? I havtn see the link :)

**Comment by alexmercerind** [comment]
@MickLesk gitter.im/harmonoid/community
