### ISSUE TITLE
Dark Theme Proposal: Follow system light/dark mode settings & remove in-app menu for light/dark mode

### ISSUE THREAD

**Issue by alexmercerind** [alexmercerind/harmonoid#27]
There's been a bit of talk with all of you regarding the dark mode & splash-screen recently.

Now that, we all agree that we cannot have a 🤍 white splash screen with the 🖤 dark theme enabled.

So, what I have added now is a dynamic splash screen that follows the system light/dark mode setting (new versions of Android have dark mode inside settings).

**We can have one of the two things:**

- Now that, we have a splash screen that follows the system light/dark mode setting. Why don't I, set the dark/light mode of the app according to system settings & remove the internal setting for light/dark mode.
- Let the splash screen follow the system light/dark mode setting & keep the in-app light/dark mode separate.

What do you think? Let me know here.

This change in my sight, will have only one negative effect that, older versions of Android which do not have the dark mode setting, will never be able to experience the dark mode.

@raitonoberu 
@mytja 
@MickLesk

**Comment by mytja** [comment]
I think, that you can keep this splashscreen android choice, but dark mode for now changable in app, since as a lot phones are still under Android 8.0, which (i think) doesn't support dark mode.
Although, I think when Android 11 releases, you can switch to dark mode by Android, since Android 8 will become unsupported at the time.
It is nice also that you do an LTS (Long Term Support) release, as I did in my project, when I moved from Python 2 to Python 3.
You can later support it for around 6 months and then drop support.
Hope this is useful
Thank you and keep succesfully building your project

**Comment by MickLesk** [comment]
I think for example, WhatsApp do the same thing like me. The Dark mode is App specific and the Splashscreen is systemlike. 
Because i switch WhatsApp to 'light' but my systemui is dark => WhatsApp Splashscreen is dark too and the WhatsApp UI is light

**Comment by alexmercerind** [comment]
Okay @MickLesk & @mytja,
I did the same thing in following commit:
alexmercerind@49aa30de0508cd810a3ee30fbf2d18ba65e54068

Now, splashscreen will follow system setting & app will follow its own setting.

**Comment by MickLesk** [comment]
Is almost the same as my example. I think this is currently the best solution. If I still see something (Flutter specific) then I will contact you :-)

How can I reach you? I have a few questions and if necessary a few remarks.

@alexmercerind

**Comment by alexmercerind** [comment]
@MickLesk,
I had to make XML a bit different than yours, as I wanted to use #121212 as background color & not complete black.

Ah yes! @MickLesk & @mytja, there is a 🎉 [Gitter](https://gitter.im/harmonoid/community) for the development of this app. You can talk to me there.

Seems pretty decent right?
<img src="https://user-images.githubusercontent.com/28951144/92505820-20200280-f222-11ea-82a1-07e9ff53083e.jpg" height="600" />

**Comment by raitonoberu** [comment]
Hi @MickLesk!
We also have a chat in Gitter: https://gitter.im/harmonoid/community
