### ISSUE TITLE
Russian translation & Suggestions for improvement

### ISSUE THREAD

**Issue by raitonoberu** [alexmercerind/harmonoid#3]
Great job!
I like your music player and I want to help you with it. I've translated globals.dart file into Russian, you can find in here: https://pastebin.com/XqfVWe0k

Also I have some suggestions for improvement. I know that the application is in the pre-release stage, and you will most likely add these features, but why not :) Note that some points are my humble opinion and you may think differently.

- [x] **One tap to search.** Now I have to tap on the search bar twice and it is inconvenient.
- [x] **Fix wrong artist name in the status bar if the album has several artists.** It's easier to show: https://ibb.co/album/BHb8zj
- [x] **Open "Now Playing" tab when tapping on notification.**
- [x] **Use async frameworks for the server ([FastAPI](https://github.com/tiangolo/fastapi), [Aiohttp](https://github.com/aio-libs/aiohttp) etc.).** Async libraries are the best way to improve performance since the server is sending http requests to the Spotify API. I can help with rewriting if you want.
- [x] **Exclude duplicate queries from history.**
- [x] **Allow the user to change the color from purple.** Just a nice bonus :) You can add a HEX entry field or (and) simple color picker.
- [x] **Allow user to abort download.**
- [x] And everyone's favourite **Dark Mode**
- [ ] **Slide to switch tab.**

Btw good luck with exams!

**Comment by alexmercerind** [comment]
😃 Thanks a lot for your feedback!

**I'm agreed with your every single feedback. And I'll add/fix everything you mentioned slowly.**

Thanks a lot, I'm glad you liked the project. The project is currently slow as well (while browsing locally)... I'll fix a lot of stuff.

A BIG thanks for providing the translation in Russian. I'll make sure to mention you in the credits.

Before leaving I'm leaving the backend of this app publicly [here](https://github.com/alexmercerind/harmonoid-service). (It is very poorly written. 😓). I have added you as a collaborator and you may accept the invitation if you are willing.

Thanks for exam wish 😊!

**Comment by alexmercerind** [comment]
The translations are working now!
![Screenshot_20200826-122714](https://user-images.githubusercontent.com/28951144/91271362-b1f62d00-e797-11ea-8d50-2efae2ac9956.jpg)

Fixed artists in notification area!
![Screenshot_20200826-122739~2](https://user-images.githubusercontent.com/28951144/91271470-dc47ea80-e797-11ea-9f7b-45b0ef4cd651.jpg)

The next pre-release v0.0.2 will have other features like background download and the things you mentioned.

**Comment by raitonoberu** [comment]
Thank you!
Can you also add a server selection function? I need it for testing a new asynchronous server..

**Comment by alexmercerind** [comment]
Hi!
I haven't compiled a release version at the moment. But I'll attach an APK with that option on your repo.

**Comment by alexmercerind** [comment]
Hi @raitonoberu ! 
It will be great if you provide me your phone's architecture (ARM64 etc.)... It will cut the size of APK by 1/2.

**Comment by raitonoberu** [comment]
Hello @alexmercerind!
Sure, my phone has Snapdragon 665 (ARMv8 64bit i guess)

**Comment by alexmercerind** [comment]
Hi @raitonoberu !
I just saw your updated list and the ideas are really great.
Now, what I have planned as a priority is to improve the downloads (like a better global management, option to abort, manage all at once, download whole album etc.). 
For these pre-release, my priority will be to improve functioning & performance, and then aesthetics.
I'll also improve my backend script to include caching of albums and tracks... Right now one has to nearly always see a loading bar even when browsing locally. That will no longer be the case.
Thanks!

**Comment by raitonoberu** [comment]
Hi @alexmercerind!
Sure, do what you see fit. I'll just add a few ideas to the list as soon as they come up.

**Comment by alexmercerind** [comment]
❎ Closing this one. 
I have to figure out how to implement swiping, other than that most features are added.
I'll make sure to add it in future.
