### ISSUE TITLE
Feature Request: Adding the option to store the audio files in local storage

### ISSUE THREAD

**Issue by Xuanghdu** [alexmercerind/harmonoid#32]
Hi @alexmercerind 

Would it be possible to choose to store the audio files in the device's local storage so that other music player could access it? Or is there other ways to access downloaded tracks outside the app?

Thanks!

**Comment by alexmercerind** [comment]
Hi @Xuanghdu !
I'm really glad that you showed your interest in the project.

Yes! It is in my plans, to share the audio files (MP3 & M4A) outside the app. Checkout #29 for more upcoming features.

At the moment, **you can still transfer the audio files manually from the directory ```Android/data/com.alexmercerind.harmonoid/. harmonoid/musicLibrary``` to your desired location.**

Although, I believe you'll love the look & feel of this app itself. **I also have plans to import/export whole music collection as a ZIP file for the purpose of backup & sharing audio files.**

Thankyou 😃!

**Comment by Xuanghdu** [comment]
@alexmercerind Thanks for your replying and clarification! I'm looking forward to the new features!
