### ISSUE TITLE
Problem with song durdation

### ISSUE THREAD

**Issue by mytja** [alexmercerind/harmonoid#35]
Hello, @alexmercerind 
I downloaded this song ![Screenshot_20200929-074546.jpg](https://user-images.githubusercontent.com/52399966/94517436-38cf7700-0228-11eb-8086-a640d2cd41e1.jpg)
And it says its dudoration is 13 seconds.
Then i played it.
![Screenshot_20200929-074540.jpg](https://user-images.githubusercontent.com/52399966/94517619-99f74a80-0228-11eb-841c-e5181514483a.jpg)
Now, it says it's 4 minutes.
I used my harmonoid-eu server, which is ytmusic server.
Can you fix this?
Thank you

**Comment by alexmercerind** [comment]
Something seems wrong...
The album you mentioned [here on YouTube](https://music.youtube.com/playlist?list=OLAK5uy_kQbMBLWm9sUrVNnooayU8ilISrC7KintI) also has a 14 second track. I don't know what is wrong... at the moment & why the app is fetching a 3:28 track... I have to see.

**Comment by raitonoberu** [comment]
You should probably close this issue because it is not related to the app itself.

**Comment by mytja** [comment]
Okay
