### ISSUE TITLE
Change main to add support to platform splashscreen.

### ISSUE THREAD

**Issue by bdlukaa** [alexmercerind/harmonoid#5]
If you set the language check in the main function before `runApp`, you can wait til the platform splashscreen to appear and do not need to create a whole new splashscreen in flutter.

Sorry for bad English :)

**Comment by alexmercerind** [comment]
It was a really great advice. In fact, I did it as well but my audio libraries stop working after calling the language detection function before the ```runApp()``` in ```main()```. 
The app worked fine, but audio playback didn't... so, closing the issue.

I'll try to do this in near future again.
Thanks for the feedback.

**Comment by alexmercerind** [comment]
Okay! This is a great change coming in the next release.
Thankyou! 😃

This greatly improves app performance, look & startup.
