### ISSUE TITLE
Cannot add to playlists and view playlists and app crashes on next startup

### ISSUE THREAD

**Issue by mytja** [alexmercerind/harmonoid#56]
**Describe the bug**
There are a lot of bugs. They are described bellow

**To Reproduce**
1. Get latest version from main branch
2. Do `flutter run`
3. Create a playlist
4. Add a song to playlist
5. Click on playlist
6. Get an error
7. Close a app
8. Open the app
9. Startup error

While I was checking JSON, I noticed, that playlist JSON is completly empty.

After clearing cache AND data, it starts working again, but only until you repeat those steps.

This error also occours when I set the server & restart the app.

I tried debugging it, but `Exceptions` aren't very detailed, but it seems the error occours somewhere here: https://github.com/alexmercerind/harmonoid/blob/master/lib/main.dart#L21-L54

**Expected behavior**
The app, changing server, JSON writing and playlists should be working fine

**Screenshots**
I created a playlist:
![playlist](https://user-images.githubusercontent.com/52399966/114261141-4fc20380-99d9-11eb-8e13-c2629969ce6e.PNG)

Clicked on a playlist:
![playlist2](https://user-images.githubusercontent.com/52399966/114261142-4fc20380-99d9-11eb-8d09-5f13a3275347.PNG)

Closed the app and reopened it:
![exception](https://user-images.githubusercontent.com/52399966/114261140-4f296d00-99d9-11eb-813d-8c853a00c699.PNG)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A21s
 - OS: Android 10 - OneUI 2.1
 - Version Latest from master

Thank you so much for your time

**Comment by raitonoberu** [comment]
Huh, I remember fixing the same bug..
https://github.com/alexmercerind/harmonoid/commit/ab2773d3dd64b190fedff37aec9903eaa05c3c57
Why is this happening again?

**Comment by mytja** [comment]
I really don't know

**Comment by alexmercerind** [comment]
@mytja are you using last "stable" build or the one from master? Some of @raitonoberu's bug-fixes were really crucial & I'm glad he took the lead.
(I added so many things at the end with little to no testing, so bug-fixes were left). I'll have a look, I'm kinda feeling good to be back here on GitHub now.

**Comment by alexmercerind** [comment]
OT: Is the Discord server still up?

**Comment by raitonoberu** [comment]
I'm sorry you're a couple of days late.

**Comment by alexmercerind** [comment]
Maybe [GitHub discussions](https://github.com/alexmercerind/harmonoid/discussions) are cool enough now. 🙂

**Comment by mytja** [comment]
I'm using latest from master
I did flutter run

**Comment by alexmercerind** [comment]
This could result in many other problems, I didn't notice that I wasn't using the `fromMap` method as every other place in the source.

**Comment by mytja** [comment]
Thank you so much
I will test it now
