### ISSUE TITLE
Song not changing automatically 

### ISSUE THREAD

**Issue by visionxStudio** [alexmercerind/harmonoid#64]
It is not changing the song automatically when one song completes. I have to keep pressing next button or manually change the song. I hope to see this fixed soon.

**Comment by alexmercerind** [comment]
@visionxStudio,
Really glad that you mentioned it, this actually is an issue with the audio library that I'm using. https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/519.

Once it will be fixed there, it will be automatically fixed in this project.
Thanks.

**Comment by alexmercerind** [comment]
Fixed
