### ISSUE TITLE
album sort

### ISSUE THREAD

**Issue by theotheroracle** [alexmercerind/harmonoid#66]
albums seem to be sorted, randomly ? the tracks are labelled correctly by number, but they don't sort or play in that order, and there doesn't seem to be any obvious way to fix it

**Comment by alexmercerind** [comment]
Hi there @theotheroracle !

Could you be a little more specific? Albums are generated in order the songs are found & you can also switch to "A to Z" order. I cannot comprehend your issue.
Thanks.

**Comment by theotheroracle** [comment]
![Screenshot_20210607-205730_Harmonoid](https://user-images.githubusercontent.com/20211219/121105930-0290c100-c7d3-11eb-9b6c-1ef1ed797dea.png)

**Comment by alexmercerind** [comment]
Hello @theotheroracle !

I've fixed the issue you told me, please download the latest [v0.0.8](https://github.com/alexmercerind/harmonoid/releases/tag/v0.0.8) version (has APK link in the dropdown).
It has few other bug fixes aswell.

Thankyou.
There is literally zero profit associated with this open source music app, don't forget to share it with friends if you are enjoying the music experience. 😃
